version: '3.7'

services:
  db:
    container_name: db
    restart: unless-stopped
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: prioritea
    ports:
      - '27018:27018'
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - internal

  api:
    container_name: api
    restart: unless-stopped
    build: ./server
    ports:
      - '3000:3000'
    env_file: ./server/.env.production
    environment:
      - NODE_ENV=production
    networks:
      - internal
    depends_on:
      - db

networks:
  internal:

volumes:
  mongo_data: { }
  mongo_config: { }