version: '3.9'
services:
  client:
    restart: always
    container_name: client
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.client
    ports:
      - "8080:80"
  server:
    depends_on:
      - db
    restart: always
    container_name: server
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.server
    ports:
      - "4000:4000"
    env_file:
      - ../packages/server/.env
    environment:
      - CORS_ORIGIN=http://localhost:8080
      - DB_URL=postgresql://postgres:postgres@db:5432/prioritea?schema=public
  db:
    restart: always
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prioritea
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
