FROM node:14-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm ci --only=production

# Bundle app source
COPY . .

COPY .env.production .env

ENV NODE_ENV production

EXPOSE 3000
CMD [ "node", "server.js" ]
USER node
